/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PressRouteImport } from './routes/press'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/press': typeof PressRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/press': typeof PressRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/press': typeof PressRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/docs'
    | '/download'
    | '/features'
    | '/press'
    | '/security'
    | '/sitemap.xml'
    | '/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/docs'
    | '/download'
    | '/features'
    | '/press'
    | '/security'
    | '/sitemap.xml'
    | '/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contact'
    | '/docs'
    | '/download'
    | '/features'
    | '/press'
    | '/security'
    | '/sitemap.xml'
    | '/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  PressRoute: typeof PressRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  PressRoute: PressRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TroubleshootingRoute: TroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
